# Generated by Django 4.2.25 on 2025-11-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('position', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=8)),
                ('joined_on', models.DateField()),
            ],
        ),
    ]
